version: '3.3'

networks:
  ip-lance-net:
    external: true

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_APP_PUBLIC_API: http://web:8000
    depends_on:
      - web
    networks:
      - ip-lance-net
    restart: always
