services:
  frontend:
    container_name: ipFrontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_APP_PUBLIC_API: http://web:8000
    networks:
      - immortal_poni_ip-lance-net
    restart: always

networks:
  immortal_poni_ip-lance-net:
    external: true
