services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_APP_PUBLIC_API: http://ipWeb:8000
    networks:
      - ip-lance-net
    restart: always

networks:
  ip-lance-net:
    driver: bridge
