name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: |
          git config user.name "silchenkoofficial"
          git config user.email "nikita.silchenko.work@yandex.ru"
      - run: npm run release
      - run: |
          git push --follow-tags https://x-access-token:${{ secrets.GH_PAT }}@github.com/ipLance-digital/immortal_poni_client.git HEAD:main
        env:
          GIT_AUTHOR_NAME: Никита
          GIT_AUTHOR_EMAIL: nikita.silchenko.work@yandex.ru
          GIT_COMMITTER_NAME: Никита
          GIT_COMMITTER_EMAIL: nikita.silchenko.work@yandex.ru
