name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # обязательно! semantic-release требует все теги

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config user.name "silchenkoofficial"
          git config user.email "nikita.silchenko.work@yandex.ru"

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIT_AUTHOR_NAME: Никита
          GIT_AUTHOR_EMAIL: nikita.silchenko.work@yandex.ru
          GIT_COMMITTER_NAME: Никита
          GIT_COMMITTER_EMAIL: nikita.silchenko.work@yandex.ru
        run: npx semantic-release
